/*
 * emoji_charset.h — the emoji font's contents, and nothing more.
 *
 * Twenty commonly-used emoji, rendered at build time (see mkemoji.c,
 * which produces emoji.bfnt) into small fixed-palette colour glyphs.
 * This array is the single source of truth for both: index i here is
 * exactly record i in emoji.bfnt, and mkemoji.c fetches art for these
 * codepoints in this order. The runtime (vt.c for cell width,
 * x11_backend.c for which glyph to draw) looks a codepoint up here to
 * get that same index -- nothing is stored per-record in emoji.bfnt
 * itself, exactly like charset.h's glyph slots aren't self-labelled
 * either.
 *
 * Two separate questions live here:
 *   emoji_index(cp)  -- do we have a bitmap for this exact emoji (and
 *                       which record is it)?
 *   emoji_wide(cp)   -- is this codepoint double-width at all? True for
 *                       the whole emoji blocks below, bitmap or not, so
 *                       cell width agrees with what wcwidth()-based
 *                       programs (readline, ncurses) assume even for
 *                       emoji we can only draw as a placeholder box.
 */
#pragma once

#include <stdint.h>

static const uint32_t emoji_charset[] = {
    0x1f600, /* 😀 grinning face                */
    0x1f602, /* 😂 face with tears of joy       */
    0x1f60d, /* 😍 heart eyes                   */
    0x1f622, /* 😢 crying face                  */
    0x1f605, /* 😅 grinning sweat               */
    0x1f60a, /* 😊 smiling face                 */
    0x1f914, /* 🤔 thinking face                */
    0x1f62d, /* 😭 loudly crying                */
    0x1f44d, /* 👍 thumbs up                    */
    0x1f44e, /* 👎 thumbs down                  */
    0x1f64f, /* 🙏 folded hands                 */
    0x1f440, /* 👀 eyes                         */
    0x1f525, /* 🔥 fire                         */
    0x1f389, /* 🎉 party popper                 */
    0x1f480, /* 💀 skull                        */
    0x26a1,  /* ⚡ HIGH VOLTAGE SIGN            */
    0x2705,  /* ✅ check mark button            */
    0x274c,  /* ❌ cross mark                   */
    0x2b50,  /* ⭐ star                         */
    0x1f4af, /* 💯 hundred points               */
    0x1f680, /* 🚀 rocket                       */
};
#define EMOJI_COUNT ((int)(sizeof(emoji_charset) / sizeof(emoji_charset[0])))

/* codepoint -> index into emoji_charset[]/emoji.bfnt, or -1 if this
 * codepoint isn't one of ours. EMOJI_COUNT is small enough that a
 * linear scan is simpler code than anything smarter, for no measurable
 * cost (same reasoning as charset.h's charset_slot() extras lookup). */
static inline int emoji_index(uint32_t cp)
{
    for (int i = 0; i < EMOJI_COUNT; i++)
        if (emoji_charset[i] == cp) return i;
    return -1;
}

/* Every double-width emoji code point, as [lo,hi] runs; generated by
 * gen_wide_ranges.py from Unicode's East Asian Width data. Each run is
 * entirely width-2 (or currently unassigned), never anything narrow, so
 * treating a whole run as wide can't disagree with wcwidth(). Runs at or
 * above 0xF000 are astral code points stored minus 0x10000 (U+1F300 ->
 * 0xF300); the two halves can't be confused because emoji_wide() only
 * ever looks up a BMP code point in 0x231A..0x2B55 or an astral one, never
 * anything in between (notably not the private-use area at U+F000+). */
static const uint16_t emoji_wide_ranges[][2] = {
    {0x231A,0x231B}, {0x23E9,0x23EC}, {0x23F0,0x23F0}, {0x23F3,0x23F3}, {0x25FD,0x25FE}, {0x2614,0x2615},
    {0x2648,0x2653}, {0x267F,0x267F}, {0x2693,0x2693}, {0x26A1,0x26A1}, {0x26AA,0x26AB}, {0x26BD,0x26BE},
    {0x26C4,0x26C5}, {0x26CE,0x26CE}, {0x26D4,0x26D4}, {0x26EA,0x26EA}, {0x26F2,0x26F3}, {0x26F5,0x26F5},
    {0x26FA,0x26FA}, {0x26FD,0x26FD}, {0x2705,0x2705}, {0x270A,0x270B}, {0x2728,0x2728}, {0x274C,0x274C},
    {0x274E,0x274E}, {0x2753,0x2755}, {0x2757,0x2757}, {0x2795,0x2797}, {0x27B0,0x27B0}, {0x27BF,0x27BF},
    {0x2B1B,0x2B1C}, {0x2B50,0x2B50}, {0x2B55,0x2B55}, {0xF004,0xF004}, {0xF0CF,0xF0CF}, {0xF18E,0xF18E},
    {0xF191,0xF19A}, {0xF200,0xF320}, {0xF32D,0xF335}, {0xF337,0xF37C}, {0xF37E,0xF393}, {0xF3A0,0xF3CA},
    {0xF3CF,0xF3D3}, {0xF3E0,0xF3F0}, {0xF3F4,0xF3F4}, {0xF3F8,0xF43E}, {0xF440,0xF440}, {0xF442,0xF4FC},
    {0xF4FF,0xF53D}, {0xF54B,0xF54E}, {0xF550,0xF567}, {0xF57A,0xF57A}, {0xF595,0xF596}, {0xF5A4,0xF5A4},
    {0xF5FB,0xF64F}, {0xF680,0xF6C5}, {0xF6CC,0xF6CC}, {0xF6D0,0xF6D2}, {0xF6D5,0xF6DF}, {0xF6EB,0xF6EC},
    {0xF6F4,0xF6FC}, {0xF7E0,0xF7F0}, {0xF90C,0xF93A}, {0xF93C,0xF945}, {0xF947,0xF9FF}, {0xFA70,0xFAF8},
};
#define EMOJI_WIDE_RANGES ((int)(sizeof(emoji_wide_ranges) / sizeof(emoji_wide_ranges[0])))

/* Is cp a double-width emoji code point (see above)? */
static inline int emoji_wide(uint32_t cp)
{
    uint32_t c;
    if (cp >= 0x1F000 && cp < 0x20000) c = cp - 0x10000;
    else if (cp >= 0x231A && cp <= 0x2B55) c = cp;
    else return 0;
    for (int i = 0; i < EMOJI_WIDE_RANGES; i++)
        if (c >= emoji_wide_ranges[i][0] && c <= emoji_wide_ranges[i][1]) return 1;
    return 0;
}
